# Change these first
owner: ALIrezanouri # Your GitHub organization or username, where this repository lives
repo: si24 # The name of this repository

sites:
  - name: بیمه سامان
    url: https://si24.ir
  - name: پرتال نمایندگان
    url: https://agent.si24.ir

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: si24
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
